export const CAMBODIA_PROVINCES = [
    { province_code: "01", province_kh: "បន្ទាយមានជ័យ", province_en: "Banteay Meanchey" },
    { province_code: "02", province_kh: "បាត់ដំបង", province_en: "Battambang" },
    { province_code: "03", province_kh: "កំពង់ចាម", province_en: "Kampong Cham" },
    { province_code: "04", province_kh: "កំពង់ឆ្នាំង", province_en: "Kampong Chhnang" },
    { province_code: "05", province_kh: "កំពង់ស្ពឺ", province_en: "Kampong Speu" },
    { province_code: "06", province_kh: "កំពង់ធំ", province_en: "Kampong Thom" },
    { province_code: "07", province_kh: "កំពត", province_en: "Kampot" },
    { province_code: "08", province_kh: "កណ្ដាល", province_en: "Kandal" },
    { province_code: "09", province_kh: "កោះកុង", province_en: "Koh Kong" },
    { province_code: "10", province_kh: "ក្រចេះ", province_en: "Kratie" },
    { province_code: "11", province_kh: "មណ្ឌលគិរី", province_en: "Mondul Kiri" },
    { province_code: "12", province_kh: "រាជធានីភ្នំពេញ", province_en: "Phnom Penh" },
    { province_code: "13", province_kh: "ព្រះវិហារ", province_en: "Preah Vihear" },
    { province_code: "14", province_kh: "ព្រៃវែង", province_en: "Prey Veng" },
    { province_code: "15", province_kh: "ពោធិ៍សាត់", province_en: "Pursat" },
    { province_code: "16", province_kh: "រតនគិរី", province_en: "Ratanak Kiri" },
    { province_code: "17", province_kh: "សៀមរាប", province_en: "Siemreap" },
    { province_code: "18", province_kh: "ព្រះសីហនុ", province_en: "Sihanoukville" },
    { province_code: "19", province_kh: "ស្ទឹងត្រែង", province_en: "Stung Treng" },
    { province_code: "20", province_kh: "ស្វាយរៀង", province_en: "Svay Rieng" },
    { province_code: "21", province_kh: "តាកែវ", province_en: "Takeo" },
    { province_code: "22", province_kh: "ឧត្ដរមានជ័យ", province_en: "Otdar Meanchey" },
    { province_code: "23", province_kh: "កែប", province_en: "Kep" },
    { province_code: "24", province_kh: "ប៉ៃលិន", province_en: "Pailin" },
    { province_code: "25", province_kh: "ត្បូងឃ្មុំ", province_en: "Tboung Khmum" }
];
